name: owlchat_keystore
description: Owlchat KeyStore Binding for Dart using dart:ffi
version: 0.1.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  ffi:
  meta:
dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^1.0.3
  test:

ffigen:
  output: 'lib/ffi.dart'
  name: 'RawKeyStore'
  description: 'Owlchat KeyStore Binding'
  array-workaround: false
  sort: true
  comments:
    style: any
    length: full
  headers:
    entry-points:
      - 'includes/keystore.h'
    include-directives:
      - '**keystore.h'
