name: owlchat_keystore
description: Owlchat KeyStore Binding for Dart using dart:ffi
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  ffigen: ^2.0.3
  pedantic: ^1.11.0
  test: ^1.16.5

ffigen:
  output: 'lib/ffi.dart'
  name: 'RawKeyStore'
  description: 'Owlchat KeyStore Binding'
  array-workaround: false
  sort: true
  comments:
    style: any
    length: full
  headers:
    entry-points:
      - 'includes/keystore.h'
    include-directives:
      - '**keystore.h'
